######
#
# ansible/role/django/tasks/main.yml
#
######

---
- name: update
  command: apt-get update

- name: apt setup tools
  apt:
    name: "{{ item }}"
  with_items:
    - python3-dev=3.5.1-3
    - python3-setuptools=20.7.0-1
    - python3-pip=8.1.1-2ubuntu0.4
    - build-essential=12.1ubuntu2
    - libssl-dev=1.0.2g-1ubuntu4.8
    - libffi-dev=3.2.1-4
    - mysql-server=5.7.19-0ubuntu0.16.04.1
    - libmysqlclient-dev=5.7.19-0ubuntu0.16.04.1
    - mysql-client=5.7.19-0ubuntu0.16.04.1
    - libapache2-mod-wsgi-py3=4.3.0-1.1build1

- name: pip setup tools
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - name: django
      version: 1.11.4
    - name: unidecode
      version: 0.4.21
    - name: argparse
      version: 1.4.0
    - name: django-extensions
      version: 1.8.1
    - name: jsonfield
      version: 2.0.2
    - name: python-dateutil
      version: 2.6.1
    - name: ipython
      version: 6.1.0
    - name: egg mysql-connector-python-rf
      version: 2.2.2
    - name: mysqlclient
      version: 1.3.10
